name: Build .jar

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build .jar
      run: |
        mvn clean compile assembly:single
        mv target/doorkey-0.1-dev-jar-with-dependencies.jar doorkey.jar

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-jar
        path: |
          doorkey.jar
        if-no-files-found: error
        compression-level: 9

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          doorkey.jar
        tag_name: main
        make_latest: true
