name: Run JUnit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install web browser
      run: |
        sudo apt update
        sudo apt install -y snapd
        snap refresh
        snap install firefox
        sudo apt install -y chromium
    - name: Install xvfb
      run: |
        sudo apt update
        sudo apt install -y xvfb
    - name: Run Tests with Maven
      run: xvfb-run --auto-servernum mvn clean test
